[package]
name = "anf"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[workspace]
members = ["crates/anf_deps", "crates/anf_gfx"]
exclude = ["crates/rust-fna3d"]

[dependencies]
anf_deps = { path = "crates/anf_deps" }
anf_gfx = { path = "crates/anf_gfx" }
log = "0.4.11"
