[package]
name = "anf"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[workspace]
members = ["crates/anf_gfx"]
exclude = ["crates/rust-fna3d"]

[dependencies]
anf_gfx = { path = "crates/anf_gfx" }
fna3d = { path = "crates/rust-fna3d/fna3d" }
sdl2 = "0.34.3"

log = "0.4.11"
