[package]
name = "anf"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[workspace]
members = ["anf_deps", "anf_gfx"]
exclude = ["rust-fna3d"]

[dependencies]
anf_deps = { path = "anf_deps" }
anf_gfx = { path = "anf_gfx" }
log = "0.4.11"
