[package]
name = "anf"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[dependencies]
fna3d = { path = "./rust-fna3d/fna3d" }
sdl2 = "0.34.2"
libc = "0.2.71"
log = "0.4.8"
env_logger = "0.7.1"
stb_image = "0.2.2"

[[bin]]
name = "anf_game"
path = "src/bin.rs"
