[package]
name = "anf_deps"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[dependencies]
fna3d = { path = "../rust-fna3d/fna3d" }
sdl2 = "0.34.2"

[lib]
path = "./lib.rs"
