[package]
name = "anf-samples"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.34.3"
fna3d = { path = "../crates/rust-fna3d/fna3d" }
anf = { path = "../" }

imgui = "0.5.0"
imgui_fna3d = { path = "crates/imgui_fna3d" }
soloud = { path = "crates/soloud-rs/soloud" }

log = "0.4.11"
num_enum = "0.5.1"
anyhow = "1.0.32"

env_logger = "0.7.1"
rand = "0.7.3"
tiled = "0.9.3"
auto_ops = "0.1.0"
