[package]
name = "fna3d_hie"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[dependencies]
fna3d = { path = "../rust-fna3d" }
log = "0.4.11"

[lib]
path = "./lib.rs"
